name: health-check

on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run health check script
      run: python health-check.py
      env:
        TOKEN: ${{ secrets.TOKEN }}